---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alloy-operator.fullname" . }}
  labels:
    {{- include "alloy-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alloy-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alloy-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if or .Values.global.image.pullSecrets .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- if .Values.global.image.pullSecrets }}
        {{ toYaml .Values.global.image.pullSecrets | nindent 8 }}
        {{- else }}
        {{ toYaml .Values.image.pullSecrets | nindent 8 }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "alloy-operator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.registry | default .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect
            - --leader-election-id={{ include "alloy-operator.fullname" . }}
            - --health-probe-bind-address=:{{ .Values.service.health.port }}
            - --metrics-bind-address=:{{ .Values.service.metrics.port }}
{{- $namespaces := .Values.namespaces }}
{{- if .Values.ownNamespaceOnly }}
  {{- $namespaces = list .Release.Namespace }}
{{- end }}
{{- if $namespaces }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ $namespaces | join "," | quote }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.health.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metrics.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.health.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.health.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
