apiVersion: v2
appVersion: 1.0.0
dependencies:
- alias: crds
  condition: crds.deploy
  name: prometheus-operator-crds
  repository: https://prometheus-community.github.io/helm-charts
  version: 21.0.0
description: Gathers metrics using Prometheus Operator Objects
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
maintainers:
- email: pete.wall@grafana.com
  name: petewall
name: feature-prometheus-operator-objects
sources:
- https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-prometheus-operator-objects
version: 1.0.0
